"""Beta-team metrics collector and report generator for AgentLog.

This wrapper consumes one or more benchmark reports generated by:
    examples/benchmark_fix_iterations.py

It produces aggregated JSON + Markdown reports and can fail CI thresholds.

Run:
    python3 examples/beta_metrics_collector.py \
      --input ./agentlog_benchmark_report.json
"""

import argparse
import json
import os
import statistics
import sys
import time
from typing import Any, Dict, List, Optional


def _load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _collect_results(reports: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    all_results: List[Dict[str, Any]] = []
    for report in reports:
        results = report.get("results", [])
        if isinstance(results, list):
            all_results.extend(results)
    return all_results


def _safe_mean(values: List[float]) -> float:
    if not values:
        return 0.0
    return round(statistics.mean(values), 4)


def _build_summary(results: List[Dict[str, Any]]) -> Dict[str, Any]:
    total_runs = len(results)
    first_try_success_count = sum(1 for r in results if r.get("first_try_success"))
    iterations = [float(r.get("iterations_to_fix", 0)) for r in results]
    times = [float(r.get("time_to_fix_ms", 0)) for r in results]

    one_shot_rate = (first_try_success_count / total_runs) if total_runs else 0.0

    per_error_type: Dict[str, Dict[str, Any]] = {}
    for result in results:
        error_type = result.get("error_type", "Unknown")
        entry = per_error_type.setdefault(
            error_type,
            {
                "count": 0,
                "first_try_success": 0,
                "avg_iterations": 0.0,
                "avg_time_ms": 0.0,
                "_iterations": [],
                "_times": [],
            },
        )
        entry["count"] += 1
        if result.get("first_try_success"):
            entry["first_try_success"] += 1
        entry["_iterations"].append(float(result.get("iterations_to_fix", 0)))
        entry["_times"].append(float(result.get("time_to_fix_ms", 0)))

    for value in per_error_type.values():
        value["avg_iterations"] = _safe_mean(value.pop("_iterations"))
        value["avg_time_ms"] = _safe_mean(value.pop("_times"))
        count = max(value["count"], 1)
        value["one_shot_rate"] = round(value["first_try_success"] / count, 4)

    return {
        "total_runs": total_runs,
        "first_try_success_count": first_try_success_count,
        "first_try_success_rate": round(one_shot_rate, 4),
        "average_iterations_to_fix": _safe_mean(iterations),
        "average_time_to_fix_ms": _safe_mean(times),
        "by_error_type": per_error_type,
    }


def _build_threshold_status(
    summary: Dict[str, Any],
    one_shot_threshold: float,
    max_avg_iterations: float,
    max_avg_time_ms: float,
) -> Dict[str, Any]:
    checks = {
        "one_shot_rate": {
            "target": one_shot_threshold,
            "actual": summary["first_try_success_rate"],
            "passed": summary["first_try_success_rate"] >= one_shot_threshold,
        },
        "avg_iterations": {
            "target": max_avg_iterations,
            "actual": summary["average_iterations_to_fix"],
            "passed": summary["average_iterations_to_fix"] <= max_avg_iterations,
        },
        "avg_time_ms": {
            "target": max_avg_time_ms,
            "actual": summary["average_time_to_fix_ms"],
            "passed": summary["average_time_to_fix_ms"] <= max_avg_time_ms,
        },
    }
    checks["all_passed"] = all(item["passed"] for item in checks.values() if isinstance(item, dict))
    return checks


def _compare_to_baseline(
    current_summary: Dict[str, Any],
    baseline_summary: Optional[Dict[str, Any]],
) -> Optional[Dict[str, Any]]:
    if baseline_summary is None:
        return None

    return {
        "first_try_success_rate_delta": round(
            current_summary["first_try_success_rate"] - baseline_summary["first_try_success_rate"],
            4,
        ),
        "average_iterations_delta": round(
            current_summary["average_iterations_to_fix"] - baseline_summary["average_iterations_to_fix"],
            4,
        ),
        "average_time_to_fix_ms_delta": round(
            current_summary["average_time_to_fix_ms"] - baseline_summary["average_time_to_fix_ms"],
            4,
        ),
    }


def _render_markdown(
    source_files: List[str],
    summary: Dict[str, Any],
    thresholds: Dict[str, Any],
    baseline_comparison: Optional[Dict[str, Any]],
) -> str:
    lines = [
        "# AgentLog Beta Metrics Report",
        "",
        f"Generated at unix: `{time.time():.3f}`",
        "",
        "## Sources",
    ]
    lines.extend([f"- `{path}`" for path in source_files])

    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- Total runs: **{summary['total_runs']}**",
            f"- First-try success rate: **{summary['first_try_success_rate'] * 100:.2f}%**",
            f"- Average iterations to fix: **{summary['average_iterations_to_fix']:.3f}**",
            f"- Average time to fix: **{summary['average_time_to_fix_ms']:.3f} ms**",
            "",
            "## Threshold checks",
            "",
            f"- One-shot rate >= {thresholds['one_shot_rate']['target'] * 100:.1f}%: {'PASS' if thresholds['one_shot_rate']['passed'] else 'FAIL'}",
            f"- Avg iterations <= {thresholds['avg_iterations']['target']}: {'PASS' if thresholds['avg_iterations']['passed'] else 'FAIL'}",
            f"- Avg time <= {thresholds['avg_time_ms']['target']} ms: {'PASS' if thresholds['avg_time_ms']['passed'] else 'FAIL'}",
            f"- Overall: **{'PASS' if thresholds['all_passed'] else 'FAIL'}**",
            "",
            "## Breakdown by error type",
            "",
            "| Error type | Runs | One-shot rate | Avg iterations | Avg time (ms) |",
            "|---|---:|---:|---:|---:|",
        ]
    )

    for error_type, data in sorted(summary["by_error_type"].items()):
        lines.append(
            f"| {error_type} | {data['count']} | {data['one_shot_rate'] * 100:.1f}% | {data['avg_iterations']:.3f} | {data['avg_time_ms']:.3f} |"
        )

    if baseline_comparison:
        lines.extend(
            [
                "",
                "## Baseline comparison",
                "",
                f"- First-try success delta: `{baseline_comparison['first_try_success_rate_delta']:+.4f}`",
                f"- Avg iterations delta: `{baseline_comparison['average_iterations_delta']:+.4f}`",
                f"- Avg time delta (ms): `{baseline_comparison['average_time_to_fix_ms_delta']:+.4f}`",
            ]
        )

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate AgentLog benchmark reports for beta teams")
    parser.add_argument("--input", nargs="+", required=True, help="Input benchmark report JSON files")
    parser.add_argument("--baseline", type=str, default="", help="Optional baseline report JSON file")
    parser.add_argument(
        "--output-json",
        type=str,
        default="./agentlog_beta_metrics_report.json",
        help="Output path for aggregated JSON",
    )
    parser.add_argument(
        "--output-md",
        type=str,
        default="./agentlog_beta_metrics_report.md",
        help="Output path for Markdown report",
    )
    parser.add_argument("--one-shot-threshold", type=float, default=0.8, help="Min acceptable one-shot rate")
    parser.add_argument("--max-avg-iterations", type=float, default=2.0, help="Max acceptable avg iterations")
    parser.add_argument("--max-avg-time-ms", type=float, default=500.0, help="Max acceptable avg time in ms")
    parser.add_argument(
        "--fail-on-threshold",
        action="store_true",
        help="Exit with status 1 if threshold checks fail",
    )
    args = parser.parse_args()

    reports = [_load_json(path) for path in args.input]
    results = _collect_results(reports)
    summary = _build_summary(results)
    thresholds = _build_threshold_status(
        summary,
        one_shot_threshold=args.one_shot_threshold,
        max_avg_iterations=args.max_avg_iterations,
        max_avg_time_ms=args.max_avg_time_ms,
    )

    baseline_summary = None
    baseline_comparison = None
    if args.baseline:
        baseline_report = _load_json(args.baseline)
        baseline_summary = _build_summary(_collect_results([baseline_report]))
        baseline_comparison = _compare_to_baseline(summary, baseline_summary)

    output = {
        "meta": {
            "generated_at_unix": time.time(),
            "source_files": [os.path.abspath(p) for p in args.input],
            "baseline_file": os.path.abspath(args.baseline) if args.baseline else None,
        },
        "summary": summary,
        "thresholds": thresholds,
        "baseline_summary": baseline_summary,
        "baseline_comparison": baseline_comparison,
    }

    output_json = os.path.abspath(args.output_json)
    with open(output_json, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)

    output_md = os.path.abspath(args.output_md)
    markdown = _render_markdown(output["meta"]["source_files"], summary, thresholds, baseline_comparison)
    with open(output_md, "w", encoding="utf-8") as f:
        f.write(markdown)

    print("=" * 72)
    print("AgentLog Beta Metrics Report")
    print("=" * 72)
    print(f"JSON: {output_json}")
    print(f"Markdown: {output_md}")
    print(f"Overall threshold status: {'PASS' if thresholds['all_passed'] else 'FAIL'}")

    if args.fail_on_threshold and not thresholds["all_passed"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
